'use strict';
const $ = (s) => document.querySelector(s);
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
$('#year').textContent = new Date().getFullYear();
$('.menu').addEventListener('click', () => { const open = $('nav').classList.toggle('open'); $('.menu').setAttribute('aria-expanded', String(open)); });
$('nav').addEventListener('click', (e) => { if (e.target.closest('a')) { $('nav').classList.remove('open'); $('.menu').setAttribute('aria-expanded', 'false'); } });
const stack = {
 ai: ['01','AI & Machine Learning','From language models to retrieval pipelines: the components behind intelligent applications.',['Python','LLMs','RAG','AI agents','Machine learning','Vector search']],
 cloud: ['02','Agent Systems','Connect model reasoning to tools, memory and bounded execution.',['Tool calling','Orchestration','Agent memory','Planning','Human review','Workflow state']],
 data: ['03','Data & Knowledge','Organize, query and retrieve information so that applications can use it meaningfully.',['SQL','Oracle Database','Vector databases','Data science','Data pipelines','Analytics']],
 dev: ['04','Software Development','The interface and service layers that turn a system design into a usable application.',['React','Next.js','TypeScript','Node.js','REST APIs','HTML & CSS']],
 infra: ['05','Prompt Engineering','Make the task, context, constraints and output contract explicit.',['System prompts','Context design','Few-shot examples','Structured outputs','Grounding','Prompt iteration']],
 tools: ['06','Evaluation & Reliability','Inspect behavior and failure paths before trusting a system in practice.',['Evaluation sets','Retrieval quality','Error analysis','Observability','Safety boundaries','Regression checks']]
};
function selectStack(key){ const [n,t,d,items]=stack[key]; $('#stack-number').textContent='DISCIPLINE / '+n; $('#stack-title').textContent=t; $('#stack-description').textContent=d; $('#stack-items').replaceChildren(...items.map(v=>{const s=document.createElement('span');s.textContent=v;return s})); document.querySelectorAll('[data-stack]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stack===key))); }
document.querySelectorAll('[data-stack]').forEach(b=>b.addEventListener('click',()=>selectStack(b.dataset.stack)));selectStack('ai');
const studies={
 rag:{title:'Knowledge, connected.',label:'001 / RETRIEVAL-AUGMENTED GENERATION',overview:'An illustrative architecture for answering questions using a controlled collection of source material.',problem:'A fluent answer is not necessarily a grounded answer. Retrieval introduces a source-selection stage before generation.',flow:['Question','Embedding','Vector retrieval','Context + LLM','Cited answer'],implementation:'Documents are split into retrievable passages. A query retrieves relevant passages, which are supplied to a language model as context. The final response should identify its supporting sources.',challenge:'Retrieval can miss the right passage, and a model can overstate what the context supports.',solution:'Evaluate retrieval separately from answer quality. Require evidence, define a no-answer path, and test ambiguous questions.',result:'Design objective: an answer that can be traced to relevant source material. No production results are claimed.'},
 cloud:{title:'Built for the flow.',label:'002 / LAYERED CLOUD APPLICATION',overview:'An illustrative application architecture that separates user experience, business logic and persistence.',problem:'When responsibilities are coupled, a change in one layer can affect the entire application.',flow:['Browser','Frontend','API service','Data store','Response'],implementation:'The interface calls an API with a clear contract. The service validates inputs and applies business rules. Persistence sits behind the service boundary, with errors surfaced explicitly to the user.',challenge:'Partial failures, network latency and changing data contracts can create a fragile user experience.',solution:'Use validation at boundaries, predictable error responses, least-privilege service access and observable request paths.',result:'Design objective: independently understandable layers with explicit contracts. This is a concept study, not a deployed application.'},
 agent:{title:'From intent to action.',label:'003 / CONTROLLED AGENT WORKFLOW',overview:'An illustrative agent workflow that separates reasoning, tool use and validation.',problem:'Autonomous tool execution needs boundaries: a plan alone does not establish that an action is correct or permitted.',flow:['Intent','Plan','Tool execution','Review','Result'],implementation:'A request creates a bounded plan. Tools expose explicit inputs and outputs. A review stage checks the result against the original request before the workflow completes.',challenge:'Tool failure, ambiguous instructions and repeated retries can move a workflow away from its intended outcome.',solution:'Define allowed actions, use bounded retries, record tool outcomes, and add human review where consequential actions require it.',result:'Design objective: accountable execution with inspectable decisions. No real-world performance claims are presented.'}
};
const caseDialog=$('#case-study');document.querySelectorAll('.study').forEach(b=>b.addEventListener('click',()=>{const s=studies[b.dataset.study];$('#case-title').textContent=s.title;$('#case-label').textContent=s.label;$('#case-body').replaceChildren();for(const [key,label] of [['overview','Overview'],['problem','Problem'],['flow','Architecture'],['implementation','Implementation approach'],['challenge','Challenge'],['solution','Design response'],['result','Intended outcome']]){const h=document.createElement('h3');h.textContent=label;$('#case-body').append(h);if(key==='flow'){const flow=document.createElement('div');flow.className='case-flow';s.flow.forEach((v,i)=>{const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0')+' / '+v;flow.append(n)});$('#case-body').append(flow)}else{const p=document.createElement('p');p.textContent=s[key];$('#case-body').append(p)}}caseDialog.showModal()}));
const palette=$('#palette');const destinations=[['About','#about'],['AI Lab','#ai-lab'],['Systems','#projects'],['Skills','#skills'],['Education','#education'],['Experience','#experience'],['Credentials','#credentials'],['Contact','#contact'],['GitHub','https://github.com/Mohammed-Arman-A']];let commandIndex=0;let commandButtons=[];
function renderCommands(){ const q=$('#command-search').value.toLowerCase().replace(/^\//,'');const list=destinations.filter(([v])=>v.toLowerCase().includes(q));$('#command-results').replaceChildren();commandIndex=0;commandButtons=list.map(([name,url])=>{const b=document.createElement('button');b.textContent='/'+name.toLowerCase();const arrow=document.createElement('span');arrow.textContent='↗';b.append(arrow);b.addEventListener('click',()=>{palette.close();if(url.startsWith('#')){location.hash=url;$(url).scrollIntoView({behavior:reduced?'instant':'smooth'});}else window.open(url,'_blank','noopener,noreferrer')});$('#command-results').append(b);return b});if(!list.length){const p=document.createElement('p');p.textContent='No matching section.';$('#command-results').append(p)}markCommand()}
function markCommand(){commandButtons.forEach((b,i)=>b.classList.toggle('selected',i===commandIndex));commandButtons[commandIndex]?.scrollIntoView({block:'nearest'});}
function openPalette(){if(palette.open)return;$('#command-search').value='';renderCommands();palette.showModal();$('#command-search').focus()}
$('.command-toggle').addEventListener('click',openPalette);$('#command-search').addEventListener('input',renderCommands);
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();palette.open?palette.close():openPalette()}if(palette.open){if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();commandIndex=(commandIndex+(e.key==='ArrowDown'?1:-1)+commandButtons.length)%Math.max(commandButtons.length,1);markCommand()}if(e.key==='Enter'){e.preventDefault();commandButtons[commandIndex]?.click()}}});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close-dialog').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()})});
if(!reduced && 'IntersectionObserver' in window){document.documentElement.classList.add('js-motion');const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));}
if('IntersectionObserver' in window){const active=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}})},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('section[id]').forEach(el=>active.observe(el));}
let scrollRatio=0;window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;scrollRatio=max>0?scrollY/max:0;$('.progress').style.width=(scrollRatio*100)+'%'},{passive:true});
// AI lab: transparent, local-only workflow simulation and prompt composition.
(()=>{
const tabs=Array.from(document.querySelectorAll('.lab-tabs [role="tab"]'));function setTab(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!selected});}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>setTab(tab));tab.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[n]);tabs[n].focus()}})});
const missions={research:[['Understand the scope','Identify the topic, audience and evidence needed.'],['Create a research plan','Break the question into source discovery, comparison and synthesis.'],['Retrieve and compare','Illustrative tool: knowledge search. Compare relevant passages and record evidence.'],['Check the response','Separate supported statements from uncertainty and identify missing sources.']],support:[['Clarify the issue','Collect symptoms, affected system and the user’s immediate goal.'],['Choose a safe path','Prioritize documented troubleshooting and define escalation boundaries.'],['Consult relevant guidance','Illustrative tool: knowledge lookup. Select applicable steps without taking account actions.'],['Validate and hand off','Check that the guidance fits the issue and flag cases that need a specialist.']],build:[['Define the application','Identify users, expected behavior and data requirements.'],['Map the agent architecture','Separate planning, tool contracts, state and evaluation.'],['Inspect proposed components','Illustrative tools: schema and API review. Check inputs, outputs and failure paths.'],['Review the design','Check testability, approval boundaries and recovery before implementation.']]};
let mode='guided',runToken=0,timers=[];const stages=Array.from(document.querySelectorAll('[data-stage]'));function clearTimers(){timers.forEach(clearTimeout);timers=[]}function reset(){runToken++;clearTimers();stages.forEach(s=>s.classList.remove('current','done'));$('#agent-log').innerHTML='<div class="log-empty"><span class="console-glyph">✳</span><p>A mission becomes a plan.<br>A plan becomes a workflow.</p><span>SELECT A MISSION TO BEGIN</span></div>';$('#agent-status').textContent='IDLE / READY';$('#run-agent').disabled=false;$('#run-agent').innerHTML='Run the workflow <span>↗</span>';$('#agent-mission').disabled=false;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=false)}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));$('#reset-agent').addEventListener('click',reset);
$('#run-agent').addEventListener('click',()=>{clearTimers();const token=++runToken;const mission=missions[$('#agent-mission').value];const execution=mode;$('#agent-log').replaceChildren();stages.forEach(s=>s.classList.remove('current','done'));$('#run-agent').disabled=true;$('#run-agent').textContent='Workflow running…';$('#agent-mission').disabled=true;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=true);function step(i){if(token!==runToken)return;stages.forEach((s,j)=>{s.classList.toggle('current',i===j);s.classList.toggle('done',j<i)});const row=document.createElement('div');row.className='log-entry';const key=document.createElement('span');key.className='log-key';key.textContent=['INTENT','PLAN','TOOLS','REVIEW'][i];const body=document.createElement('div');const h=document.createElement('strong');h.textContent=mission[i][0];const desc=document.createElement('span');desc.textContent=mission[i][1]+(i===2?(execution==='guided'?' Human review boundary is included before consequential tool actions.':' Execution remains limited to explicitly allowed tools.'):'');body.append(h,desc);row.append(key,body);$('#agent-log').append(row);$('#agent-status').textContent='RUNNING / '+String(i+1).padStart(2,'0');if(i<3)timers.push(setTimeout(()=>step(i+1),reduced?100:1100));else timers.push(setTimeout(()=>{if(token!==runToken)return;stages.forEach(s=>{s.classList.remove('current');s.classList.add('done')});$('#agent-status').textContent='SIMULATION COMPLETE / 04 STAGES';$('#run-agent').disabled=false;$('#run-agent').innerHTML='Run again <span>↺</span>';$('#agent-mission').disabled=false;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=false)},reduced?100:700))}step(0)});
function compose(){const task=$('#prompt-task').value.trim()||'Describe the task to complete.';const lines=['ROLE\nYou are an '+$('#prompt-role').value.toLowerCase()+'.','TASK\n'+task,'CONTEXT\nUse the supplied requirements and reference material. Ask for information that would materially change the design.'];const rules=['Separate assumptions from verified information.','Stay within the stated scope and tool permissions.'];if($('#prompt-evidence').checked)rules.push('Support factual claims with evidence. State uncertainty and do not invent missing information.');if($('#prompt-review').checked)rules.push('Include validation steps, failure cases and review boundaries.');lines.push('CONSTRAINTS\n'+rules.map((v,i)=>(i+1)+'. '+v).join('\n'));lines.push('OUTPUT\n'+$('#prompt-format').value+'.');$('#prompt-preview').textContent=lines.join('\n\n');$('#prompt-status').textContent='LIVE PREVIEW'}['prompt-role','prompt-task','prompt-format','prompt-evidence','prompt-review'].forEach(id=>document.getElementById(id).addEventListener('input',compose));compose();$('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#prompt-preview').textContent);$('#prompt-status').textContent='COPIED TO CLIPBOARD'}catch{$('#prompt-status').textContent='SELECT THE PREVIEW TEXT TO COPY'}});
})();

// Subtle pointer depth on system studies; no hover-only content.
if(!reduced&&matchMedia('(pointer:fine)').matches)document.querySelectorAll('.architecture').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${-y*4}deg) rotateY(${x*4}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});

// Cinematic chapter reveals, accessible education tabs and credential views.
(()=>{
 const education={overview:'Qualifications, institutions and study dates will complete this record.',learning:'Areas of interest: AI engineering, agent systems, prompt design and reliable software.'};
 const tabs=Array.from(document.querySelectorAll('[data-education]'));
 function select(tab){tabs.forEach(b=>{b.setAttribute('aria-selected',String(b===tab));b.tabIndex=b===tab?0:-1});$('#edu-note').setAttribute('aria-labelledby',tab.id);$('#edu-note p').textContent=education[tab.dataset.education]}
 tabs.forEach((b,i)=>{b.addEventListener('click',()=>select(b));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;select(tabs[j]);tabs[j].focus()})});
 const views={all:['ALL CREDENTIALS','Room for every milestone.','Certification documents and digital badges will appear here with their issuer, date and verification link.'],certification:['CERTIFICATIONS','The evidence behind the learning.','Full certification documents will appear here, including the issuing organization, issue date and verification details.'],badge:['DIGITAL BADGES','Small symbols. Meaningful learning.','Digital badges will appear here with their issuer and a link to the original credential.']};
 document.querySelectorAll('[data-credential]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-credential]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const [label,title,copy]=views[b.dataset.credential];$('#credential-view').textContent=label;$('#credential-heading').textContent=title;$('#credential-copy').textContent=copy}));
 if(!reduced&&'IntersectionObserver'in window){document.body.classList.add('cinematic-ready');const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-frame');reveal.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.education-layout,.credential-gallery,.experience-layout').forEach(el=>{el.classList.add('cinematic-enter');reveal.observe(el)})}
 if('IntersectionObserver'in window){const chapters=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)document.querySelectorAll('.chapter-nav a').forEach(a=>a.setAttribute('aria-current',String(a.getAttribute('href')==='#'+e.target.id)))}),{rootMargin:'-20% 0px -45% 0px'});document.querySelectorAll('main>section[id]').forEach(el=>chapters.observe(el))}
 if(!reduced&&matchMedia('(hover:hover) and (pointer:fine)').matches)document.querySelectorAll('.depth-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1100px) rotateX(${-y*5}deg) rotateY(${x*7}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
})();
