'use strict';
const $ = (s) => document.querySelector(s);
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
$('#year').textContent = new Date().getFullYear();
$('.menu').addEventListener('click', () => { const open = $('nav').classList.toggle('open'); $('.menu').setAttribute('aria-expanded', String(open)); });
$('nav').addEventListener('click', (e) => { if (e.target.closest('a')) { $('nav').classList.remove('open'); $('.menu').setAttribute('aria-expanded', 'false'); } });
const stack = {
 ai: ['01','AI & Machine Learning','From language models to retrieval pipelines: the components behind intelligent applications.',['Python','LLMs','RAG','AI agents','Machine learning','Vector search']],
 cloud: ['02','Agent Systems','Connect model reasoning to tools, memory and bounded execution.',['Tool calling','Orchestration','Agent memory','Planning','Human review','Workflow state']],
 data: ['03','Data & Knowledge','Organize, query and retrieve information so that applications can use it meaningfully.',['SQL','Oracle Database','Vector databases','Data science','Data pipelines','Analytics']],
 dev: ['04','Software Development','The interface and service layers that turn a system design into a usable application.',['React','Next.js','TypeScript','Node.js','REST APIs','HTML & CSS']],
 infra: ['05','Prompt Engineering','Make the task, context, constraints and output contract explicit.',['System prompts','Context design','Few-shot examples','Structured outputs','Grounding','Prompt iteration']],
 tools: ['06','Evaluation & Reliability','Inspect behavior and failure paths before trusting a system in practice.',['Evaluation sets','Retrieval quality','Error analysis','Observability','Safety boundaries','Regression checks']]
};
function selectStack(key){ const [n,t,d,items]=stack[key]; $('#stack-number').textContent='DISCIPLINE / '+n; $('#stack-title').textContent=t; $('#stack-description').textContent=d; $('#stack-items').replaceChildren(...items.map(v=>{const s=document.createElement('span');s.textContent=v;return s})); document.querySelectorAll('[data-stack]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stack===key))); }
document.querySelectorAll('[data-stack]').forEach(b=>b.addEventListener('click',()=>selectStack(b.dataset.stack)));selectStack('ai');
const studies={
 rag:{title:'Knowledge, connected.',label:'001 / RETRIEVAL-AUGMENTED GENERATION',overview:'An illustrative architecture for answering questions using a controlled collection of source material.',problem:'A fluent answer is not necessarily a grounded answer. Retrieval introduces a source-selection stage before generation.',flow:['Question','Embedding','Vector retrieval','Context + LLM','Cited answer'],implementation:'Documents are split into retrievable passages. A query retrieves relevant passages, which are supplied to a language model as context. The final response should identify its supporting sources.',challenge:'Retrieval can miss the right passage, and a model can overstate what the context supports.',solution:'Evaluate retrieval separately from answer quality. Require evidence, define a no-answer path, and test ambiguous questions.',result:'Design objective: an answer that can be traced to relevant source material. No production results are claimed.'},
 cloud:{title:'Built for the flow.',label:'002 / LAYERED CLOUD APPLICATION',overview:'An illustrative application architecture that separates user experience, business logic and persistence.',problem:'When responsibilities are coupled, a change in one layer can affect the entire application.',flow:['Browser','Frontend','API service','Data store','Response'],implementation:'The interface calls an API with a clear contract. The service validates inputs and applies business rules. Persistence sits behind the service boundary, with errors surfaced explicitly to the user.',challenge:'Partial failures, network latency and changing data contracts can create a fragile user experience.',solution:'Use validation at boundaries, predictable error responses, least-privilege service access and observable request paths.',result:'Design objective: independently understandable layers with explicit contracts. This is a concept study, not a deployed application.'},
 agent:{title:'From intent to action.',label:'003 / CONTROLLED AGENT WORKFLOW',overview:'An illustrative agent workflow that separates reasoning, tool use and validation.',problem:'Autonomous tool execution needs boundaries: a plan alone does not establish that an action is correct or permitted.',flow:['Intent','Plan','Tool execution','Review','Result'],implementation:'A request creates a bounded plan. Tools expose explicit inputs and outputs. A review stage checks the result against the original request before the workflow completes.',challenge:'Tool failure, ambiguous instructions and repeated retries can move a workflow away from its intended outcome.',solution:'Define allowed actions, use bounded retries, record tool outcomes, and add human review where consequential actions require it.',result:'Design objective: accountable execution with inspectable decisions. No real-world performance claims are presented.'}
};
const caseDialog=$('#case-study');document.querySelectorAll('.study').forEach(b=>b.addEventListener('click',()=>{const s=studies[b.dataset.study];$('#case-title').textContent=s.title;$('#case-label').textContent=s.label;$('#case-body').replaceChildren();for(const [key,label] of [['overview','Overview'],['problem','Problem'],['flow','Architecture'],['implementation','Implementation approach'],['challenge','Challenge'],['solution','Design response'],['result','Intended outcome']]){const h=document.createElement('h3');h.textContent=label;$('#case-body').append(h);if(key==='flow'){const flow=document.createElement('div');flow.className='case-flow';s.flow.forEach((v,i)=>{const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0')+' / '+v;flow.append(n)});$('#case-body').append(flow)}else{const p=document.createElement('p');p.textContent=s[key];$('#case-body').append(p)}}caseDialog.showModal()}));
const palette=$('#palette');const destinations=[['About','#about'],['AI Lab','#ai-lab'],['Systems','#projects'],['Skills','#skills'],['Experience','#experience'],['Credentials','#credentials'],['Contact','#contact'],['GitHub','https://github.com/Mohammed-Arman-A']];let commandIndex=0;let commandButtons=[];
function renderCommands(){ const q=$('#command-search').value.toLowerCase().replace(/^\//,'');const list=destinations.filter(([v])=>v.toLowerCase().includes(q));$('#command-results').replaceChildren();commandIndex=0;commandButtons=list.map(([name,url])=>{const b=document.createElement('button');b.textContent='/'+name.toLowerCase();const arrow=document.createElement('span');arrow.textContent='↗';b.append(arrow);b.addEventListener('click',()=>{palette.close();if(url.startsWith('#')){location.hash=url;$(url).scrollIntoView({behavior:reduced?'instant':'smooth'});}else window.open(url,'_blank','noopener,noreferrer')});$('#command-results').append(b);return b});if(!list.length){const p=document.createElement('p');p.textContent='No matching section.';$('#command-results').append(p)}markCommand()}
function markCommand(){commandButtons.forEach((b,i)=>b.classList.toggle('selected',i===commandIndex));commandButtons[commandIndex]?.scrollIntoView({block:'nearest'});}
function openPalette(){if(palette.open)return;$('#command-search').value='';renderCommands();palette.showModal();$('#command-search').focus()}
$('.command-toggle').addEventListener('click',openPalette);$('#command-search').addEventListener('input',renderCommands);
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();palette.open?palette.close():openPalette()}if(palette.open){if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();commandIndex=(commandIndex+(e.key==='ArrowDown'?1:-1)+commandButtons.length)%Math.max(commandButtons.length,1);markCommand()}if(e.key==='Enter'){e.preventDefault();commandButtons[commandIndex]?.click()}}});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close-dialog').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()})});
if(!reduced && 'IntersectionObserver' in window){document.documentElement.classList.add('js-motion');const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));}
if('IntersectionObserver' in window){const active=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}})},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('section[id]').forEach(el=>active.observe(el));}
let scrollRatio=0;window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;scrollRatio=max>0?scrollY/max:0;$('.progress').style.width=(scrollRatio*100)+'%'},{passive:true});
// Native WebGL: no external 3D library download or runtime dependency.
(()=>{const canvas=$('#core');const gl=canvas.getContext('webgl',{alpha:true,antialias:true,powerPreference:'low-power'});if(!gl){canvas.hidden=true;$('.core-fallback').hidden=false;return}
const vertex=`attribute vec3 position;attribute float intensity;uniform float angle;uniform vec2 pointer;uniform float aspect;uniform float pixelRatio;uniform float visualMode;varying mediump float glow;void main(){float a=angle;mat3 ry=mat3(cos(a),0.,sin(a),0.,1.,0.,-sin(a),0.,cos(a));float b=.24+pointer.y*.14;mat3 rx=mat3(1.,0.,0.,0.,cos(b),-sin(b),0.,sin(b),cos(b));vec3 source=position;if(visualMode>1.5){float t=position.y*9.;source=vec3(cos(t)*.62,position.y,sin(t)*.62);}else if(visualMode>.5){float cluster=position.y>.25?0.:position.y<-.25?2.:1.;float t=cluster*2.094;source=position*.4+vec3(cos(t)*.6,sin(t)*.5,0.);}vec3 p=rx*ry*source;float perspective=3.2/(3.2-p.z);gl_Position=vec4((p.x+pointer.x*.05)*perspective/aspect,p.y*perspective,0.,1.);gl_PointSize=(2.2+intensity*4.0)*pixelRatio*perspective;glow=intensity*(.65+p.z*.2);}`;
const fragment=`precision mediump float;uniform bool points;varying mediump float glow;void main(){float alpha=glow;if(points){float d=length(gl_PointCoord-vec2(.5));if(d>.5)discard;alpha*=smoothstep(.5,.05,d);}gl_FragColor=vec4(.58,.82,.94,alpha);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error('Shader compilation failed');return s}
let program;try{program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Shader link failed')}catch{canvas.hidden=true;$('.core-fallback').hidden=false;return}gl.useProgram(program);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.clearColor(0,0,0,0);
const mobile=matchMedia('(max-width:760px)').matches;const count=mobile?58:100;const nodes=[];let seed=42;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
// A layered computational lattice, with a connected octahedral core.
for(let i=0;i<count;i++){const theta=random()*Math.PI*2;const y=random()*1.7-.85;const radius=.62+random()*.12;nodes.push([Math.cos(theta)*radius,y,Math.sin(theta)*radius,.6+random()*.4])}const core=[[.25,0,0],[-.25,0,0],[0,.32,0],[0,-.32,0],[0,0,.25],[0,0,-.25]];core.forEach(p=>nodes.push([...p,1]));const lines=[];for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const d=Math.hypot(...nodes[i].slice(0,3).map((v,k)=>v-nodes[j][k]));if(d<.31||(i>=count&&j>=count&&d<.55)){lines.push(...nodes[i].slice(0,3),.15,...nodes[j].slice(0,3),.15)}}
// Elliptical orbital connections around the lattice.
for(let orbit=0;orbit<3;orbit++){const tilt=orbit*.8;for(let i=0;i<90;i++){for(const t of [i/90*Math.PI*2,(i+1)/90*Math.PI*2]){const x=Math.cos(t)*.96;const y=Math.sin(t)*.30;const z=Math.sin(t)*.64;lines.push(x,Math.cos(tilt)*y-Math.sin(tilt)*z,Math.sin(tilt)*y+Math.cos(tilt)*z,.19)}}}
const pos=gl.getAttribLocation(program,'position'),intensity=gl.getAttribLocation(program,'intensity');const uniforms={};['angle','pointer','aspect','pixelRatio','points','visualMode'].forEach(n=>uniforms[n]=gl.getUniformLocation(program,n));function buffer(data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);return b}const lineBuffer=buffer(lines),pointBuffer=buffer(nodes.flat());let coreVisual=0;document.querySelectorAll('[data-core]').forEach(b=>b.addEventListener('click',()=>{coreVisual={network:0,agents:1,reasoning:2}[b.dataset.core];document.querySelectorAll('[data-core]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw(performance.now())}));let tx=0,ty=0,px=0,py=0,visible=true,raf=0,start=performance.now(),last=0;
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();tx=(e.clientX-r.left)/r.width*2-1;ty=-((e.clientY-r.top)/r.height*2-1);if(reduced)draw(performance.now())});canvas.addEventListener('pointerleave',()=>{tx=ty=0;if(reduced)draw(performance.now())});
function resize(){const r=canvas.getBoundingClientRect();const dpr=Math.min(devicePixelRatio||1,mobile?1.4:1.8);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);gl.viewport(0,0,canvas.width,canvas.height);gl.uniform1f(uniforms.aspect,r.width/r.height);gl.uniform1f(uniforms.pixelRatio,dpr);if(reduced)draw(performance.now())}function bind(b){gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,16,0);gl.enableVertexAttribArray(intensity);gl.vertexAttribPointer(intensity,1,gl.FLOAT,false,16,12)}
function draw(now){px+=(tx-px)*.025;py+=(ty-py)*.025;gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform1f(uniforms.visualMode,coreVisual);gl.uniform1f(uniforms.angle,(reduced?.4:(now-start)*.000045)+px*.12+scrollRatio*.8);gl.uniform2f(uniforms.pointer,px,py);bind(lineBuffer);gl.uniform1i(uniforms.points,0);gl.drawArrays(gl.LINES,0,lines.length/4);bind(pointBuffer);gl.uniform1i(uniforms.points,1);gl.drawArrays(gl.POINTS,0,nodes.length)}function loop(now){raf=0;if(!visible||document.hidden||reduced)return;if(now-last>1000/(mobile?24:40)){draw(now);last=now}raf=requestAnimationFrame(loop)}function run(){if(!raf&&visible&&!document.hidden&&!reduced)raf=requestAnimationFrame(loop)}if('ResizeObserver'in window)new ResizeObserver(resize).observe(canvas);else addEventListener('resize',resize);if('IntersectionObserver'in window)new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(!visible&&raf){cancelAnimationFrame(raf);raf=0}else run()}).observe(canvas);document.addEventListener('visibilitychange',()=>{if(document.hidden&&raf){cancelAnimationFrame(raf);raf=0}else run()});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(raf);canvas.hidden=true;$('.core-fallback').hidden=false});resize();draw(start);run();})();

// AI lab: transparent, local-only workflow simulation and prompt composition.
(()=>{
const tabs=Array.from(document.querySelectorAll('.lab-tabs [role="tab"]'));function setTab(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!selected});}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>setTab(tab));tab.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[n]);tabs[n].focus()}})});
const missions={research:[['Understand the scope','Identify the topic, audience and evidence needed.'],['Create a research plan','Break the question into source discovery, comparison and synthesis.'],['Retrieve and compare','Illustrative tool: knowledge search. Compare relevant passages and record evidence.'],['Check the response','Separate supported statements from uncertainty and identify missing sources.']],support:[['Clarify the issue','Collect symptoms, affected system and the user’s immediate goal.'],['Choose a safe path','Prioritize documented troubleshooting and define escalation boundaries.'],['Consult relevant guidance','Illustrative tool: knowledge lookup. Select applicable steps without taking account actions.'],['Validate and hand off','Check that the guidance fits the issue and flag cases that need a specialist.']],build:[['Define the application','Identify users, expected behavior and data requirements.'],['Map the agent architecture','Separate planning, tool contracts, state and evaluation.'],['Inspect proposed components','Illustrative tools: schema and API review. Check inputs, outputs and failure paths.'],['Review the design','Check testability, approval boundaries and recovery before implementation.']]};
let mode='guided',runToken=0,timers=[];const stages=Array.from(document.querySelectorAll('[data-stage]'));function clearTimers(){timers.forEach(clearTimeout);timers=[]}function reset(){runToken++;clearTimers();stages.forEach(s=>s.classList.remove('current','done'));$('#agent-log').innerHTML='<div class="log-empty"><span class="console-glyph">✳</span><p>A mission becomes a plan.<br>A plan becomes a workflow.</p><span>SELECT A MISSION TO BEGIN</span></div>';$('#agent-status').textContent='IDLE / READY';$('#run-agent').disabled=false;$('#run-agent').innerHTML='Run the workflow <span>↗</span>';$('#agent-mission').disabled=false;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=false)}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));$('#reset-agent').addEventListener('click',reset);
$('#run-agent').addEventListener('click',()=>{clearTimers();const token=++runToken;const mission=missions[$('#agent-mission').value];const execution=mode;$('#agent-log').replaceChildren();stages.forEach(s=>s.classList.remove('current','done'));$('#run-agent').disabled=true;$('#run-agent').textContent='Workflow running…';$('#agent-mission').disabled=true;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=true);function step(i){if(token!==runToken)return;stages.forEach((s,j)=>{s.classList.toggle('current',i===j);s.classList.toggle('done',j<i)});const row=document.createElement('div');row.className='log-entry';const key=document.createElement('span');key.className='log-key';key.textContent=['INTENT','PLAN','TOOLS','REVIEW'][i];const body=document.createElement('div');const h=document.createElement('strong');h.textContent=mission[i][0];const desc=document.createElement('span');desc.textContent=mission[i][1]+(i===2?(execution==='guided'?' Human review boundary is included before consequential tool actions.':' Execution remains limited to explicitly allowed tools.'):'');body.append(h,desc);row.append(key,body);$('#agent-log').append(row);$('#agent-status').textContent='RUNNING / '+String(i+1).padStart(2,'0');if(i<3)timers.push(setTimeout(()=>step(i+1),reduced?100:1100));else timers.push(setTimeout(()=>{if(token!==runToken)return;stages.forEach(s=>{s.classList.remove('current');s.classList.add('done')});$('#agent-status').textContent='SIMULATION COMPLETE / 04 STAGES';$('#run-agent').disabled=false;$('#run-agent').innerHTML='Run again <span>↺</span>';$('#agent-mission').disabled=false;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=false)},reduced?100:700))}step(0)});
function compose(){const task=$('#prompt-task').value.trim()||'Describe the task to complete.';const lines=['ROLE\nYou are an '+$('#prompt-role').value.toLowerCase()+'.','TASK\n'+task,'CONTEXT\nUse the supplied requirements and reference material. Ask for information that would materially change the design.'];const rules=['Separate assumptions from verified information.','Stay within the stated scope and tool permissions.'];if($('#prompt-evidence').checked)rules.push('Support factual claims with evidence. State uncertainty and do not invent missing information.');if($('#prompt-review').checked)rules.push('Include validation steps, failure cases and review boundaries.');lines.push('CONSTRAINTS\n'+rules.map((v,i)=>(i+1)+'. '+v).join('\n'));lines.push('OUTPUT\n'+$('#prompt-format').value+'.');$('#prompt-preview').textContent=lines.join('\n\n');$('#prompt-status').textContent='LIVE PREVIEW'}['prompt-role','prompt-task','prompt-format','prompt-evidence','prompt-review'].forEach(id=>document.getElementById(id).addEventListener('input',compose));compose();$('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#prompt-preview').textContent);$('#prompt-status').textContent='COPIED TO CLIPBOARD'}catch{$('#prompt-status').textContent='SELECT THE PREVIEW TEXT TO COPY'}});
})();

// CPU projection of a real 3D lattice: preserves interactive depth on devices without WebGL.
(()=>{const wrap=$('.core-wrap'),fallback=$('.core-fallback');if(fallback.hidden)return;const canvas=document.createElement('canvas');canvas.setAttribute('role','img');canvas.setAttribute('aria-label','Rotating interactive 3D agent network. Choose network, agents or reasoning mode.');const ctx=canvas.getContext('2d');if(!ctx)return;fallback.replaceChildren(canvas);let width=600,height=520,dpr=1,angle=.5,px=0,py=0,tx=0,ty=0,visual='network',visible=true,raf=0,last=0;const mobile=matchMedia('(max-width:760px)').matches;const nodes=[];const total=mobile?62:100;for(let i=0;i<total;i++){const theta=i*2.399963;const y=1-(i/(total-1))*2;const r=Math.sqrt(1-y*y);nodes.push([Math.cos(theta)*r*.72,y*.85,Math.sin(theta)*r*.72])}const core=[[.28,0,0],[-.28,0,0],[0,.35,0],[0,-.35,0],[0,0,.28],[0,0,-.28]];const edgePairs=[];nodes.forEach((a,i)=>nodes.slice(i+1).forEach((b,j)=>{if(Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])<.36)edgePairs.push([i,i+j+1])}));
function transform(p){let [x,y,z]=p;const a=angle+px*.3+scrollRatio*.5;let xx=x*Math.cos(a)+z*Math.sin(a),zz=-x*Math.sin(a)+z*Math.cos(a);const b=.22+py*.3;const yy=y*Math.cos(b)-zz*Math.sin(b);zz=y*Math.sin(b)+zz*Math.cos(b);const scale=3.6/(3.6-zz);const size=Math.min(width,height)*.34;return [width*.5+xx*scale*size,height*.5-yy*scale*size,zz,scale]}
function line(a,b,opacity,color='139,174,231'){const pa=transform(a),pb=transform(b);ctx.strokeStyle='rgba('+color+','+opacity+')';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(pa[0],pa[1]);ctx.lineTo(pb[0],pb[1]);ctx.stroke()}
function draw(){ctx.clearRect(0,0,width,height);px+=(tx-px)*.055;py+=(ty-py)*.055;const halo=ctx.createRadialGradient(width*.5,height*.5,0,width*.5,height*.5,Math.min(width,height)*.45);halo.addColorStop(0,'rgba(98,136,211,.12)');halo.addColorStop(1,'rgba(98,136,211,0)');ctx.fillStyle=halo;ctx.fillRect(0,0,width,height);let points=nodes;if(visual==='agents')points=nodes.map((p,i)=>{const c=i%3,t=c/3*Math.PI*2;return[p[0]*.32+Math.cos(t)*.68,p[1]*.42+Math.sin(t)*.55,p[2]*.45]});if(visual==='reasoning')points=nodes.map((p,i)=>{const t=i/total*Math.PI*6;return[Math.cos(t)*.62,(i/total-.5)*1.7,Math.sin(t)*.62]});if(visual==='network')edgePairs.forEach(([a,b])=>line(points[a],points[b],.28));else for(let i=0;i<points.length-1;i++)line(points[i],points[i+1],visual==='agents'?.2:.4);for(let orbit=0;orbit<3;orbit++){for(let i=0;i<90;i++){const p=[];for(const t of [i/90*Math.PI*2,(i+1)/90*Math.PI*2]){const tilt=orbit*.8;p.push([Math.cos(t)*1.02,Math.sin(t)*Math.sin(tilt)*.72,Math.sin(t)*Math.cos(tilt)*.72])}line(p[0],p[1],.18)}}for(let i=0;i<core.length;i++)for(let j=i+1;j<core.length;j++)if(Math.hypot(...core[i].map((v,k)=>v-core[j][k]))<.6)line(core[i],core[j],.7,'187,212,255');points.map(transform).sort((a,b)=>a[2]-b[2]).forEach((p,i)=>{const glow=.5+p[2]*.3;ctx.fillStyle='rgba(182,210,255,'+Math.max(.2,glow)+')';ctx.beginPath();ctx.arc(p[0],p[1],(1.6+p[2]*.5)*p[3],0,Math.PI*2);ctx.fill();if(i%17===0){ctx.fillStyle='rgba(145,176,225,.035)';ctx.beginPath();ctx.arc(p[0],p[1],8,0,Math.PI*2);ctx.fill()}})}
function resize(){const r=wrap.getBoundingClientRect();width=r.width;height=r.height;dpr=Math.min(devicePixelRatio||1,mobile?1.4:1.8);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}function frame(now){raf=0;if(!visible||document.hidden||reduced)return;if(now-last>1000/(mobile?24:40)){angle+=.0015;draw();last=now}raf=requestAnimationFrame(frame)}function run(){if(!raf&&visible&&!document.hidden&&!reduced)raf=requestAnimationFrame(frame)}wrap.addEventListener('pointermove',e=>{const r=wrap.getBoundingClientRect();tx=((e.clientX-r.left)/r.width-.5)*2;ty=-((e.clientY-r.top)/r.height-.5)*2;if(reduced){px=tx;py=ty;draw()}});wrap.addEventListener('pointerleave',()=>{tx=ty=0;if(reduced){px=py=0;draw()}});document.querySelectorAll('[data-core]').forEach(b=>b.addEventListener('click',()=>{visual=b.dataset.core;document.querySelectorAll('[data-core]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw()}));if('ResizeObserver'in window)new ResizeObserver(resize).observe(wrap);if('IntersectionObserver'in window)new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(!visible&&raf){cancelAnimationFrame(raf);raf=0}else run()}).observe(wrap);document.addEventListener('visibilitychange',()=>{if(document.hidden&&raf){cancelAnimationFrame(raf);raf=0}else run()});resize();run()})();
// Subtle pointer depth on system studies; no hover-only content.
if(!reduced&&matchMedia('(pointer:fine)').matches)document.querySelectorAll('.architecture').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${-y*4}deg) rotateY(${x*4}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
