// Loading transition, layered parallax, staggered entrances and tactile controls.
(()=>{
 const themeButton=document.querySelector('.theme-toggle');
 function themeLabel(){const light=document.documentElement.dataset.theme==='light';themeButton.setAttribute('aria-pressed',String(light));themeButton.setAttribute('aria-label',light?'Switch to dark theme':'Switch to light theme');themeButton.querySelector('span').textContent=light?'☾':'☀';document.querySelector('meta[name="theme-color"]').setAttribute('content',light?'#f5f3ff':'#060711')}
 themeLabel();themeButton.addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=theme;try{localStorage.setItem('arman-theme',theme)}catch{}themeLabel();document.dispatchEvent(new Event('portfolio-theme-change'))});
 const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)');
 const loader=document.querySelector('.site-loader');let dismissed=false;
 function enter(){if(dismissed)return;dismissed=true;document.documentElement.classList.remove('booting');loader.setAttribute('aria-hidden','true');loader.inert=true;setTimeout(()=>loader.remove(),reducedQuery.matches?0:750)}
 loader.querySelector('button').addEventListener('click',enter);
 if(document.readyState==='complete')setTimeout(enter,180);else addEventListener('load',()=>setTimeout(enter,180),{once:true});setTimeout(enter,1800);
 const reveals=document.querySelectorAll('.project,.thinking-card,.stack-layout,.lab-panel,.experience-record,.credential-toolbar,.hero-copy');
 if(!reducedQuery.matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('scene-visible');observer.unobserve(e.target)}}),{threshold:.08});reveals.forEach((el,i)=>{el.classList.add('scene-reveal');el.style.setProperty('--reveal-delay',`${i%3*80}ms`);observer.observe(el)})}
 let request=0,x=0,y=0;const ambience=document.querySelector('.ambient-layer');
 function update(){request=0;const s=Math.min(scrollY,innerHeight*2);ambience.style.setProperty('--drift-x',`${x*28}px`);ambience.style.setProperty('--drift-y',`${y*20-s*.045}px`);document.documentElement.style.setProperty('--hero-shift',`${Math.min(scrollY,innerHeight)*-.07}px`);document.querySelector('header').classList.toggle('scrolled',scrollY>35)}
 function schedule(){if(!request&&!reducedQuery.matches)request=requestAnimationFrame(update)}
 addEventListener('scroll',schedule,{passive:true});addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;x=e.clientX/innerWidth-.5;y=e.clientY/innerHeight-.5;schedule()},{passive:true});
 reducedQuery.addEventListener('change',e=>{if(e.matches){cancelAnimationFrame(request);request=0;ambience.style.setProperty('--drift-x','0px');ambience.style.setProperty('--drift-y','0px');document.documentElement.style.setProperty('--hero-shift','0px');document.querySelectorAll('.scene-reveal').forEach(el=>el.classList.add('scene-visible'))}});
 if(matchMedia('(hover:hover) and (pointer:fine)').matches&&!reducedQuery.matches)document.querySelectorAll('.hero-actions .primary,.contact-row .primary').forEach(button=>{button.addEventListener('pointermove',e=>{const r=button.getBoundingClientRect();button.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.1}px,${(e.clientY-r.top-r.height/2)*.15}px)`});button.addEventListener('pointerleave',()=>button.style.transform='')});
 document.addEventListener('click',e=>{const button=e.target.closest('button,.primary');if(!button||reducedQuery.matches||button.disabled)return;const r=button.getBoundingClientRect(),ripple=document.createElement('i');ripple.className='tap-ripple';ripple.setAttribute('aria-hidden','true');ripple.style.left=`${e.detail?e.clientX-r.left:r.width/2}px`;ripple.style.top=`${e.detail?e.clientY-r.top:r.height/2}px`;button.append(ripple);setTimeout(()=>ripple.remove(),650)});
 document.querySelectorAll('.thinking-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--spot-x',`${e.clientX-r.left}px`);card.style.setProperty('--spot-y',`${e.clientY-r.top}px`)})});
})();
