import * as THREE from 'three';
// A real-time 3D stage: illuminated solids, depth, orbital motion and a scroll camera.
const canvas=document.createElement('canvas');canvas.id='immersive-stage';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);
const motion=matchMedia('(prefers-reduced-motion: reduce)'),small=matchMedia('(max-width:760px)').matches;
let paused=motion.matches,mode='network',chapter=0,px=0,py=0,tx=0,ty=0,time=0,raf=0,last=0;
const control=document.createElement('button');control.className='stage-motion';document.body.append(control);
function label(){control.textContent=paused?'PLAY MOTION ↗':'PAUSE MOTION Ⅱ';control.setAttribute('aria-label',paused?'Play scene animation':'Pause scene animation')}label();
let render,resize;
try{
 const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:!small,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,small?1.2:1.6));renderer.setClearColor(0x060711,0);
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(document.documentElement.dataset.theme==='light'?0xebe5ff:0x060711,.045);document.addEventListener('portfolio-theme-change',()=>{scene.fog.color.setHex(document.documentElement.dataset.theme==='light'?0xebe5ff:0x060711);render?.()});const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100);camera.position.z=10;
 scene.add(new THREE.AmbientLight(0x8c77ff,1.5));const light=new THREE.PointLight(0xb39cff,100,25);light.position.set(-3,4,5);scene.add(light);const green=new THREE.PointLight(0xc4ff65,70,25);green.position.set(4,-2,4);scene.add(green);
 const group=new THREE.Group();scene.add(group);
 const body=new THREE.Mesh(new THREE.TorusKnotGeometry(1.25,.4,small?100:180,20,2,3),new THREE.MeshStandardMaterial({color:0x5d64b5,metalness:.72,roughness:.2,emissive:0x152442,emissiveIntensity:.5}));group.add(body);
 const inner=new THREE.Mesh(new THREE.IcosahedronGeometry(.62,1),new THREE.MeshStandardMaterial({color:0xd8ff79,metalness:.45,roughness:.18,emissive:0x8ba836,emissiveIntensity:.3}));group.add(inner);
 const rings=[];for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(2.1+i*.22,.025,8,100),new THREE.MeshBasicMaterial({color:i===1?0x8dcbdc:0x999cde,transparent:true,opacity:.55}));ring.rotation.set(i*.8,.3+i*.7,0);group.add(ring);rings.push(ring)}
 const satellites=[];for(let i=0;i<7;i++){const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.12+i%3*.05),new THREE.MeshStandardMaterial({color:i%2?0xb999ff:0xd1ff87,metalness:.5,roughness:.25}));group.add(mesh);satellites.push(mesh)}
 const starGeometry=new THREE.BufferGeometry();const values=new Float32Array((small?180:420)*3);for(let i=0;i<values.length;i++)values[i]=(Math.random()-.5)*32;starGeometry.setAttribute('position',new THREE.BufferAttribute(values,3));const stars=new THREE.Points(starGeometry,new THREE.PointsMaterial({color:0x8469a5,size:.022,transparent:true,opacity:.55}));scene.add(stars);
 render=()=>{const hero=chapter===0;group.position.x=small?0:hero?2.4:-2.1;group.position.y=small?hero?-1.8:0:0;group.scale.setScalar(mode==='agents'?.9:1);group.rotation.x=py*.22+Math.sin(time*.21)*.15;group.rotation.y=time*.24+px*.3;group.rotation.z=Math.sin(time*.15)*.12;body.rotation.y=time*.17;body.rotation.x=mode==='reasoning'?Math.PI/2:time*.11;inner.rotation.set(time*.5,time*.7,0);rings.forEach((r,i)=>r.rotation.z=time*(.08+i*.04));satellites.forEach((s,i)=>{const a=time*(.3+i*.025)+i*Math.PI*2/7,r=mode==='agents'?2.9:2.6;s.position.set(Math.cos(a)*r,Math.sin(a*1.3)*1.65,Math.sin(a)*r);s.rotation.set(time*.5+i,time*.4,0)});camera.position.x+=(px*.35-camera.position.x)*.04;camera.position.y+=(py*.25-camera.position.y)*.04;camera.position.z+=((hero?10:12)-camera.position.z)*.04;stars.rotation.y=time*.015;renderer.render(scene,camera)};
 resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);render()};
}catch{
 // Solid, shaded perspective rendering for browsers where WebGL is unavailable.
 const replacement=document.createElement('canvas');replacement.id=canvas.id;replacement.setAttribute('aria-hidden','true');canvas.replaceWith(replacement);const g=replacement.getContext('2d');let w=innerWidth,h=innerHeight,dpr=1;
 const knots=Array.from({length:110},(_,i)=>{const t=i/110*Math.PI*2;return{x:(2+Math.cos(t*3)*.55)*Math.cos(t*2),y:(2+Math.cos(t*3)*.55)*Math.sin(t*2),z:Math.sin(t*3)*.8,t}});
 render=()=>{g.clearRect(0,0,w,h);const cx=small?w*.5:chapter===0?w*.74:w*.3,cy=small&&chapter===0?h*.75:h*.48,scale=Math.min(w,h)*(small?.12:.105);const a=time*.23+px*.3,b=.5+py*.3;
 const points=knots.map(p=>{const source=mode==='reasoning'?{x:Math.cos(p.t*3)*1.6,y:(p.t/6.28-.5)*4.8,z:Math.sin(p.t*3)*1.6}:p;const x=source.x*Math.cos(a)+source.z*Math.sin(a),z=-source.x*Math.sin(a)+source.z*Math.cos(a),y=source.y*Math.cos(b)-z*Math.sin(b),zz=p.y*Math.sin(b)+z*Math.cos(b),d=8/(8-zz);return{x:cx+x*scale*d,y:cy+y*scale*d,z:zz,d,t:p.t}}).sort((a,b)=>a.z-b.z);
 const glow=g.createRadialGradient(cx,cy,0,cx,cy,scale*4);glow.addColorStop(0,'rgba(71,115,178,.16)');glow.addColorStop(1,'rgba(131,74,255,0)');g.fillStyle=glow;g.fillRect(0,0,w,h);
 for(const p of points){const r=scale*.37*p.d,light=35+(p.z+3)*7;const fill=g.createRadialGradient(p.x-r*.35,p.y-r*.4,0,p.x,p.y,r);fill.addColorStop(0,`hsl(240,65%,${Math.min(85,light+24)}%)`);fill.addColorStop(.4,`hsl(238,55%,${light}%)`);fill.addColorStop(1,'#17213b');g.fillStyle=fill;g.beginPath();g.arc(p.x,p.y,r,0,Math.PI*2);g.fill()}
 for(let i=0;i<3;i++){g.save();g.translate(cx,cy);g.rotate(time*.1+i*1.05);g.strokeStyle=i===1?'rgba(151,210,225,.6)':'rgba(174,177,232,.45)';g.lineWidth=1.5;g.beginPath();g.ellipse(0,0,scale*(2.9+i*.17),scale*.8,0,0,Math.PI*2);g.stroke();g.restore()}
 for(let i=0;i<7;i++){const t=time*.35+i*.898,rr=scale*(mode==='agents'?3.5:3),x=cx+Math.cos(t)*rr,y=cy+Math.sin(t)*rr*.65,r=scale*.12;const fill=g.createRadialGradient(x-r*.4,y-r*.4,0,x,y,r);fill.addColorStop(0,'#efffd2');fill.addColorStop(.45,i%2?'#b9a0ff':'#b3e66b');fill.addColorStop(1,'#362759');g.fillStyle=fill;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill()}
 };
 resize=()=>{w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,1.3);replacement.width=w*dpr;replacement.height=h*dpr;g.setTransform(dpr,0,0,dpr,0,0);render()};
}
function frame(now){raf=0;if(paused||document.hidden)return;if(now-last>1000/(small?24:40)){time+=last?Math.min(.06,(now-last)/1000):0;last=now;px+=(tx-px)*.05;py+=(ty-py)*.05;render()}raf=requestAnimationFrame(frame)}
function run(){last=0;if(!raf&&!paused&&!document.hidden)raf=requestAnimationFrame(frame)}
control.addEventListener('click',()=>{paused=!paused;label();cancelAnimationFrame(raf);raf=0;run()});motion.addEventListener('change',e=>{paused=e.matches;label();cancelAnimationFrame(raf);raf=0;render();run()});document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(raf);raf=0;run()});document.addEventListener('portfolio-theme-change',()=>render());addEventListener('resize',resize);addEventListener('pointermove',e=>{if(e.pointerType==='mouse'&&!motion.matches){tx=e.clientX/innerWidth*2-1;ty=e.clientY/innerHeight*2-1}},{passive:true});
document.querySelectorAll('[data-core]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.core;document.querySelectorAll('[data-core]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()}));
new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){chapter=e.target.id==='home'?0:1;render()}}),{rootMargin:'-20% 0px -55% 0px'}).observe(document.querySelector('#home'));
addEventListener('scroll',()=>{chapter=scrollY<innerHeight*.65?0:1;if(paused)render()},{passive:true});resize();run();
// A lightweight cursor glow with a short energy ribbon.
if(matchMedia('(hover:hover) and (pointer:fine)').matches){const glow=document.createElement('div');glow.className='energy-cursor';document.body.append(glow);let trail=[];let cursorRaf=0;const ribbon=document.createElement('canvas');ribbon.id='energy-ribbon';ribbon.setAttribute('aria-hidden','true');document.body.append(ribbon);const c=ribbon.getContext('2d');function size(){ribbon.width=innerWidth;ribbon.height=innerHeight}size();addEventListener('resize',size);function paint(now){cursorRaf=0;c.clearRect(0,0,ribbon.width,ribbon.height);trail=trail.filter(p=>now-p.t<320);c.lineCap='round';for(let i=1;i<trail.length;i++){c.strokeStyle=`rgba(174,132,255,${(1-(now-trail[i].t)/320)*.5})`;c.lineWidth=3;c.beginPath();c.moveTo(trail[i-1].x,trail[i-1].y);c.lineTo(trail[i].x,trail[i].y);c.stroke()}if(trail.length)cursorRaf=requestAnimationFrame(paint)}addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||motion.matches)return;glow.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;glow.style.opacity='1';trail.push({x:e.clientX,y:e.clientY,t:performance.now()});trail=trail.slice(-30);if(!cursorRaf)cursorRaf=requestAnimationFrame(paint)},{passive:true});document.documentElement.addEventListener('pointerleave',()=>glow.style.opacity='0');motion.addEventListener('change',e=>{if(e.matches){glow.style.opacity='0';trail=[];c.clearRect(0,0,ribbon.width,ribbon.height)}})}
