import * as THREE from 'three';
// A real-time 3D stage: illuminated solids, depth, orbital motion and a scroll camera.
const canvas=document.createElement('canvas');canvas.id='immersive-stage';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);
const motion=matchMedia('(prefers-reduced-motion: reduce)');let small=matchMedia('(max-width:760px)').matches;
function stageRect(){const el=document.querySelector('#portfolio-view:not([hidden]) .core-wrap');return el&&chapter===0?el.getBoundingClientRect():null}
let paused=motion.matches,mode='network',chapter=0,px=0,py=0,tx=0,ty=0,time=0,raf=0,last=0;
const control=document.createElement('button');control.className='stage-motion';document.body.append(control);
function label(){control.textContent=paused?'PLAY MOTION ↗':'PAUSE MOTION Ⅱ';control.setAttribute('aria-label',paused?'Play scene animation':'Pause scene animation')}label();
let render,resize;
try{
 const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:!small,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,small?1.2:1.6));renderer.setClearColor(0x060711,0);
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(document.documentElement.dataset.theme==='light'?0xebe5ff:0x060711,.045);document.addEventListener('portfolio-theme-change',()=>{scene.fog.color.setHex(document.documentElement.dataset.theme==='light'?0xebe5ff:0x060711);render?.()});const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100);camera.position.z=10;
 scene.add(new THREE.AmbientLight(0x8c77ff,1.5));const light=new THREE.PointLight(0xb39cff,100,25);light.position.set(-3,4,5);scene.add(light);const green=new THREE.PointLight(0xc4ff65,70,25);green.position.set(4,-2,4);scene.add(green);
 const group=new THREE.Group();scene.add(group);
 const models={network:new THREE.Group(),agents:new THREE.Group(),reasoning:new THREE.Group()};Object.values(models).forEach(m=>group.add(m));
 const nodePositions=Array.from({length:42},(_,i)=>{const t=i*2.399963,r=Math.sqrt(1-Math.pow(1-2*(i+.5)/42,2));return new THREE.Vector3(Math.cos(t)*r*2, (1-2*(i+.5)/42)*2,Math.sin(t)*r*1.35)});
 const nodes=[];nodePositions.forEach((p,i)=>{const n=new THREE.Mesh(new THREE.SphereGeometry(i%7===0?.16:.09,16,12),new THREE.MeshStandardMaterial({color:i%3?0x9b9cff:0xb7ff85,emissive:i%3?0x454ba0:0x538b33,emissiveIntensity:1,metalness:.4,roughness:.3}));n.position.copy(p);models.network.add(n);nodes.push(n)});
 nodePositions.forEach((p,i)=>nodePositions.slice(i+1).forEach(q=>{if(p.distanceTo(q)<1.2){const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([p,q]),new THREE.LineBasicMaterial({color:0x8ca4ff,transparent:true,opacity:.4}));models.network.add(l)}}));
 const shell=new THREE.MeshStandardMaterial({color:0x797fd1,metalness:.7,roughness:.25});const face=new THREE.MeshStandardMaterial({color:0x101a31,metalness:.4,roughness:.22});const mint=new THREE.MeshBasicMaterial({color:0xc2ff88});
 function box(w,h,d,x,y,z,mat=shell){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);models.agents.add(m);return m}
 box(2.5,1.8,1.2,0,.9,0);box(2.08,1.22,.08,0,.95,.64,face);box(1.65,1.45,1,0,-.85,0);box(.42,1.2,.5,-1.22,-.7,0);const arm=box(.42,1.2,.5,1.22,-.65,0);box(.5,.55,.6,-.48,-1.83,0);box(.5,.55,.6,.48,-1.83,0);box(.08,.5,.08,0,2.04,0,mint);box(.28,.2,.24,0,2.35,0,mint);box(.37,.28,.07,-.49,1.05,.72,mint);box(.37,.28,.07,.49,1.05,.72,mint);box(.5,.06,.08,0,.64,.72,mint);box(.32,.32,.08,0,-.6,.54,mint);
 const logicPoints=[new THREE.Vector3(0,2,0),new THREE.Vector3(-1.3,.65,.3),new THREE.Vector3(1.3,.65,-.3),new THREE.Vector3(-2,-1.15,.4),new THREE.Vector3(-.65,-1.15,-.5),new THREE.Vector3(.65,-1.15,.5),new THREE.Vector3(2,-1.15,-.4)];const logicNodes=[];logicPoints.forEach((p,i)=>{const m=new THREE.Mesh(new THREE.OctahedronGeometry(i===0?.38:.27),new THREE.MeshStandardMaterial({color:i%2?0xac9bff:0xbfff89,emissive:i%2?0x493a88:0x426c28,emissiveIntensity:.65,metalness:.5,roughness:.25}));m.position.copy(p);models.reasoning.add(m);logicNodes.push(m)});[ [0,1],[0,2],[1,3],[1,4],[2,5],[2,6]].forEach(([a,b])=>models.reasoning.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([logicPoints[a],logicPoints[b]]),new THREE.LineBasicMaterial({color:0x99afff,transparent:true,opacity:.8}))));
 const starGeometry=new THREE.BufferGeometry();const values=new Float32Array((small?180:420)*3);for(let i=0;i<values.length;i++)values[i]=(Math.random()-.5)*32;starGeometry.setAttribute('position',new THREE.BufferAttribute(values,3));const stars=new THREE.Points(starGeometry,new THREE.PointsMaterial({color:0x8469a5,size:.022,transparent:true,opacity:.55}));scene.add(stars);
 render=()=>{const hero=chapter===0;const rect=stageRect();const viewH=2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*camera.position.z;const scale=rect?Math.min(rect.width/innerWidth*viewH*camera.aspect/5.4,rect.height/innerHeight*viewH/5.6):1;group.scale.setScalar(scale);group.position.set(rect?((rect.left+rect.width/2)/innerWidth-.5)*viewH*camera.aspect:small?0:hero?2.4:-2.1,rect?(.5-(rect.top+rect.height/2)/innerHeight)*viewH:0,0);Object.entries(models).forEach(([key,m])=>m.visible=key===mode);group.rotation.set(py*.12,mode==='network'?time*.18+px*.25:Math.sin(time*.35)*.18+px*.25,0);nodes.forEach((n,i)=>n.scale.setScalar(1+.2*Math.sin(time*2+i)));arm.rotation.z=Math.sin(time*1.5)*.18;models.agents.position.y=Math.sin(time*.8)*.1;logicNodes.forEach((n,i)=>{n.rotation.y=time*.5;n.scale.setScalar(1+.12*Math.sin(time*2-i))});camera.position.x+=(px*.25-camera.position.x)*.04;camera.position.y+=(py*.2-camera.position.y)*.04;camera.position.z+=((hero?10:12)-camera.position.z)*.04;stars.rotation.y=time*.015;renderer.render(scene,camera)};
 resize=()=>{small=matchMedia('(max-width:760px)').matches;renderer.setPixelRatio(Math.min(devicePixelRatio||1,small?1.2:1.6));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);render()};
}catch{
 // Solid, shaded perspective rendering for browsers where WebGL is unavailable.
 const replacement=document.createElement('canvas');replacement.id=canvas.id;replacement.setAttribute('aria-hidden','true');canvas.replaceWith(replacement);const g=replacement.getContext('2d');let w=innerWidth,h=innerHeight,dpr=1;
 const neural=Array.from({length:42},(_,i)=>{const y=1-2*(i+.5)/42,r=Math.sqrt(1-y*y),t=i*2.399963;return{x:Math.cos(t)*r*2,y:y*2,z:Math.sin(t)*r*1.35}});
 const logic=[{x:0,y:2,z:0},{x:-1.3,y:.65,z:.3},{x:1.3,y:.65,z:-.3},{x:-2,y:-1.15,z:.4},{x:-.65,y:-1.15,z:-.5},{x:.65,y:-1.15,z:.5},{x:2,y:-1.15,z:-.4}];
 render=()=>{g.clearRect(0,0,w,h);const rect=stageRect(),cx=rect?rect.left+rect.width/2:small?w*.5:chapter===0?w*.74:w*.3,cy=rect?rect.top+rect.height/2:h*.48,scale=rect?Math.min(rect.width/5.4,rect.height/5.6):Math.min(w,h)*(small?.12:.105),a=mode==='network'?time*.18+px*.25:Math.sin(time*.35)*.18+px*.25;
 function project(p){const x=p.x*Math.cos(a)+p.z*Math.sin(a),z=-p.x*Math.sin(a)+p.z*Math.cos(a),d=8/(8-z);return{x:cx+x*scale*d,y:cy-p.y*scale*d,z,d}}
 function line(p,q,color='rgba(150,172,255,.45)'){const u=project(p),v=project(q);g.strokeStyle=color;g.lineWidth=1.5;g.beginPath();g.moveTo(u.x,u.y);g.lineTo(v.x,v.y);g.stroke()}
 function sphere(p,r,color){const u=project(p),radius=r*scale*u.d,fill=g.createRadialGradient(u.x-radius*.35,u.y-radius*.4,0,u.x,u.y,radius);fill.addColorStop(0,'#f0edff');fill.addColorStop(.35,color);fill.addColorStop(1,'#27334c');g.fillStyle=fill;g.beginPath();g.arc(u.x,u.y,radius,0,Math.PI*2);g.fill()}
 const glow=g.createRadialGradient(cx,cy,0,cx,cy,scale*3.5);glow.addColorStop(0,'rgba(105,115,226,.16)');glow.addColorStop(1,'rgba(100,70,200,0)');g.fillStyle=glow;g.fillRect(0,0,w,h);
 if(mode==='network'){neural.forEach((p,i)=>neural.slice(i+1).forEach(q=>{if(Math.hypot(p.x-q.x,p.y-q.y,p.z-q.z)<1.2)line(p,q)}));neural.map((p,i)=>({p,i})).sort((u,v)=>project(u.p).z-project(v.p).z).forEach(({p,i})=>sphere(p,(i%7===0?.16:.09)*(1+.2*Math.sin(time*2+i)),i%3?'#949eff':'#bbf58e'))}
 else if(mode==='reasoning'){[[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]].forEach(([i,j])=>line(logic[i],logic[j],'rgba(151,177,255,.8)'));logic.forEach((p,i)=>{sphere(p,(i===0?.33:.23)*(1+.1*Math.sin(time*2-i)),i%2?'#ae9aff':'#b4f68b');const u=project(p);g.fillStyle=document.documentElement.dataset.theme==='light'?'#4e4275':'#e2dbff';g.font='10px monospace';g.textAlign='center';g.fillText(['INTENT','PLAN','CHECK','TOOL','REVIEW','REFINE','RESULT'][i],u.x,u.y+scale*.48)})}
 else{function box(x,y,z,bw,bh,bd,color){const verts=[];for(let dz of [-1,1])for(let dy of [-1,1])for(let dx of [-1,1])verts.push(project({x:x+dx*bw/2,y:y+dy*bh/2,z:z+dz*bd/2}));[[0,1,3,2],[0,4,5,1],[1,5,7,3],[2,3,7,6],[4,6,7,5]].map((ids,i)=>({ids,i,z:ids.reduce((s,j)=>s+verts[j].z,0)/4})).sort((u,v)=>u.z-v.z).forEach(({ids,i})=>{g.fillStyle=[ '#434e85','#6975ac','#4b568d','#929ce0',color][i];g.strokeStyle='#afb9ee88';g.lineWidth=.7;g.beginPath();ids.forEach((j,k)=>k?g.lineTo(verts[j].x,verts[j].y):g.moveTo(verts[j].x,verts[j].y));g.closePath();g.fill();g.stroke()})}
 const bob=Math.sin(time*.8)*.1;box(-.48,-1.83+bob,0,.5,.55,.6,'#8993d0');box(.48,-1.83+bob,0,.5,.55,.6,'#8993d0');box(-1.22,-.7+bob,0,.42,1.2,.5,'#a4a8e2');box(1.22,-.65+bob,0,.42,1.2,.5,'#a4a8e2');box(0,-.85+bob,0,1.65,1.45,1,'#8993d0');box(0,.9+bob,0,2.5,1.8,1.2,'#9aa4e4');box(0,.95+bob,.65,2.08,1.22,.06,'#14243a');line({x:0,y:1.8+bob,z:0},{x:0,y:2.35+bob,z:0},'#c4ff8f');sphere({x:0,y:2.35+bob,z:0},.13,'#c4ff8f');sphere({x:-.49,y:1.05+bob,z:.73},.16,'#c4ff8f');sphere({x:.49,y:1.05+bob,z:.73},.16,'#c4ff8f');line({x:-.25,y:.63+bob,z:.75},{x:.25,y:.63+bob,z:.75},'#c4ff8f');sphere({x:0,y:-.6+bob,z:.56},.12,'#c4ff8f')}
 };
 resize=()=>{small=matchMedia('(max-width:760px)').matches;w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,1.3);replacement.width=w*dpr;replacement.height=h*dpr;g.setTransform(dpr,0,0,dpr,0,0);render()};
}
function frame(now){raf=0;if(paused||document.hidden)return;if(now-last>1000/(small?24:40)){time+=last?Math.min(.06,(now-last)/1000):0;last=now;px+=(tx-px)*.05;py+=(ty-py)*.05;render()}raf=requestAnimationFrame(frame)}
function run(){last=0;if(!raf&&!paused&&!document.hidden)raf=requestAnimationFrame(frame)}
control.addEventListener('click',()=>{paused=!paused;label();cancelAnimationFrame(raf);raf=0;run()});motion.addEventListener('change',e=>{paused=e.matches;label();cancelAnimationFrame(raf);raf=0;render();run()});document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(raf);raf=0;run()});document.addEventListener('portfolio-theme-change',()=>render());addEventListener('resize',resize);addEventListener('pointermove',e=>{if(e.pointerType==='mouse'&&!motion.matches){tx=e.clientX/innerWidth*2-1;ty=e.clientY/innerHeight*2-1}},{passive:true});
function setMode(next){if(!['network','agents','reasoning'].includes(next))return;mode=next;document.querySelector('#immersive-stage').dataset.scene=mode;document.querySelectorAll('[data-core]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.core===mode)));const labels={network:['NEURAL NETWORK / LIVE','CONNECTED NEURONS / SIGNAL FLOW'],agents:['AI AGENT / LIVE','AUTONOMOUS BOT / READY TO BUILD'],reasoning:['REASONING GRAPH / LIVE','INTENT → PLAN → CHECK → RESULT']};document.querySelector('.scene-caption').lastChild.textContent=' '+labels[mode][0];document.querySelector('#scene-description').textContent=labels[mode][1];render()}
 document.querySelectorAll('[data-core]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.core)));document.addEventListener('scene-mode-request',e=>setMode(e.detail));document.addEventListener('portfolio-view-change',()=>{chapter=0;render()});
new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){chapter=e.target.id==='home'?0:1;render()}}),{rootMargin:'-20% 0px -55% 0px'}).observe(document.querySelector('#home'));
addEventListener('scroll',()=>{chapter=scrollY<innerHeight*.65?0:1;if(paused)render()},{passive:true});resize();setMode(mode);run();
// A lightweight cursor glow with a short energy ribbon.
if(matchMedia('(hover:hover) and (pointer:fine)').matches){const glow=document.createElement('div');glow.className='energy-cursor';document.body.append(glow);let trail=[];let cursorRaf=0;const ribbon=document.createElement('canvas');ribbon.id='energy-ribbon';ribbon.setAttribute('aria-hidden','true');document.body.append(ribbon);const c=ribbon.getContext('2d');function size(){ribbon.width=innerWidth;ribbon.height=innerHeight}size();addEventListener('resize',size);function paint(now){cursorRaf=0;c.clearRect(0,0,ribbon.width,ribbon.height);trail=trail.filter(p=>now-p.t<320);c.lineCap='round';for(let i=1;i<trail.length;i++){c.strokeStyle=`rgba(174,132,255,${(1-(now-trail[i].t)/320)*.5})`;c.lineWidth=3;c.beginPath();c.moveTo(trail[i-1].x,trail[i-1].y);c.lineTo(trail[i].x,trail[i].y);c.stroke()}if(trail.length)cursorRaf=requestAnimationFrame(paint)}addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||motion.matches)return;glow.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;glow.style.opacity='1';trail.push({x:e.clientX,y:e.clientY,t:performance.now()});trail=trail.slice(-30);if(!cursorRaf)cursorRaf=requestAnimationFrame(paint)},{passive:true});document.documentElement.addEventListener('pointerleave',()=>glow.style.opacity='0');motion.addEventListener('change',e=>{if(e.matches){glow.style.opacity='0';trail=[];c.clearRect(0,0,ribbon.width,ribbon.height)}})}
