// Portfolio and AI Lab are separate views with shared theme and motion settings.
(()=>{
 const $=s=>document.querySelector(s),portfolio=$('#portfolio-view'),lab=$('#lab-view');
 const labIds=new Set(Array.from(lab.querySelectorAll('section[id]')).map(el=>el.id));
 function setView(view,scroll=true){const changed=document.body.dataset.workspace!==view,isLab=view==='lab';portfolio.hidden=isLab;lab.hidden=!isLab;document.body.dataset.workspace=view;document.querySelectorAll('[data-workspace]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.workspace===view)));$('.chapter-nav').hidden=isLab;$('nav[aria-label="Main navigation"]').hidden=isLab;document.dispatchEvent(new CustomEvent('portfolio-view-change',{detail:view}));if(scroll)window.scrollTo({top:0,behavior:'instant'});if(changed)document.dispatchEvent(new CustomEvent('scene-mode-request',{detail:isLab?'agents':'network'}));}
 document.querySelectorAll('[data-workspace]').forEach(b=>b.addEventListener('click',()=>{setView(b.dataset.workspace);history.replaceState(null,'',b.dataset.workspace==='lab'?'#lab-home':'#home')}));
 function route(id,scroll=false){if(!document.getElementById(id))return;setView(labIds.has(id)?'lab':'portfolio',scroll)}
 document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const id=a.getAttribute('href').slice(1)||'home';route(id)});
 document.addEventListener('portfolio-route',e=>route(e.detail));addEventListener('hashchange',()=>route(location.hash.slice(1)||'home'));route(location.hash.slice(1)||'home');
 const answers=[[/educ|bca|mca|manipal|degree|study|college/i,'Arman completed a Bachelor of Computer Applications specializing in data and artificial intelligence in 2025. He is studying an MCA at Manipal Academy of Higher Education, focused on AI, cloud and data engineering, with completion expected in 2027.'],[/experience|dxc|ey|intern|job|role|team/i,'Arman’s experience includes a full-stack development internship at EY and an Infrastructure Analyst role at DXC Technology from January 2026. He joined the XCPA Core Team two months after starting, building agents and bots with application teams and automating use cases.'],[/skill|agent|workflow|ai|interest|prompt/i,'His interests center on AI engineering, agent creation, stateful workflows, prompt design and team automation. The Skills section explores AI, agent systems, data, development, prompt engineering and evaluation.'],[/cert|badge|anthropic|cloud/i,'The portfolio currently lists self-reported architecture, cloud/AI and ChatGPT certification entries. Exact titles, documents and verification links are pending. Digital badges have not been added yet.'],[/project|system|build/i,'The AI Lab includes local workflow and prompt demos, plus illustrative RAG, cloud and agent architecture studies. Those studies are concepts, not claims of completed client projects.'],[/hello|hi\b|hey|help/i,'Hello! I can help you explore Arman’s education, work experience, AI interests and certification entries. I’m a local portfolio guide, not a connected language model.']];
 function message(text,kind){const p=document.createElement('p');p.className='guide-message '+kind;p.textContent=text;$('#guide-log').append(p);while($('#guide-log').children.length>14)$('#guide-log').firstElementChild.remove();$('#guide-log').scrollTop=$('#guide-log').scrollHeight}
 function ask(q){q=q.trim();if(!q)return;message(q,'question');message(answers.find(([pattern])=>pattern.test(q))?.[1]||'I can answer questions about education, experience, AI interests, projects and credentials using this portfolio. Try one of those topics.','answer');$('#guide-input').value=''}
 $('#guide-form').addEventListener('submit',e=>{e.preventDefault();ask($('#guide-input').value)});document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>ask(b.dataset.question)));
 const remixes=[['The Cosmic Meeting Translator','Turn meeting notes into a clear action plan, explained by a very organized astronaut.','Notes + task list','Ask before assigning tasks'],['The Dramatic Bug Detective','Investigate a bug report like a noir detective. Collect evidence, list suspects and propose a test before declaring the culprit.','Bug report + logs','Separate evidence from guesses'],['The Polite Chaos Coordinator','Turn an overflowing inbox into a calm plan, while sounding like a tiny robot in a very large hat.','Messages + priorities','Draft only; do not send'],['The Rubber Duck Researcher','Explain a technical topic to a rubber duck, then turn the explanation into a source-grounded learning checklist.','Reference notes + checklist','Do not invent sources'],['The Spreadsheet Sorcerer','Find confusing spreadsheet fields and propose a cleanup plan, with the enthusiasm of a wizard who loves tidy columns.','Table + validation rules','Review before editing data'],['The Sleepy Support Sidekick','Triage a support request into questions and next steps, in the voice of a sleepy but surprisingly competent cat.','Request + approved notes','Ask when context is missing']];
 let current=0,count=1;
 $('#remix-button').addEventListener('click',()=>{current=(current+1+Math.floor(Math.random()*(remixes.length-1)))%remixes.length;count++;const [title,mission,tools,rule]=remixes[current];$('#remix-title').textContent=title;$('#remix-mission').textContent=mission;$('#remix-tools').textContent='TOOLS / '+tools.toUpperCase();$('#remix-rule').textContent='RULE / '+rule.toUpperCase();$('#remix-number').textContent='REMIX / '+String(count).padStart(3,'0');$('#remix-status').textContent='PLAYFUL CONCEPT / LOCAL GENERATOR';$('.remix-machine').classList.remove('remixed');requestAnimationFrame(()=>$('.remix-machine').classList.add('remixed'))});
 $('#remix-copy').addEventListener('click',async()=>{const [title,mission,tools,rule]=remixes[current];const prompt=`ROLE\n${title}\n\nTASK\n${mission}\n\nCONTEXT\n${tools}\n\nBOUNDARY\n${rule}.\n\nOUTPUT\nA concise plan with assumptions and review steps.`;try{await navigator.clipboard.writeText(prompt);$('#remix-status').textContent='PROMPT COPIED'}catch{$('#remix-status').textContent='COPY THE VISIBLE IDEA AND BOUNDARIES'}});
})();
